### ISSUE TITLE
Copy URL broken

### ISSUE THREAD

**Issue by Keith94** [Flozad/copy-all-urls-extension#1]
The button doesn't copy anything

**Comment by rdonkin** [comment]
I'm having the same issue - using Copy URL button doesn't give any feedback and doesn't copy selected tabs.

@Flozad _muchas gracias_for creating this extension to continue Copy All URLs one!  I hope you can fix this issue 🤞

**Comment by Flozad** [comment]
@Keith94 @rdonkin thanks for bringing this up. Can you give me more context.

Does it work with simpler tabs?
Are you adding some customization to copy format?
Can you share url example of what you are trying to copy and it’s failing?

**Comment by Flozad** [comment]
@rdonkin @Keith94 I rolled out a new version (1.1.0) with the latest commit on the Chrome store. Let me know if this fixed the issue on your devices.

**Comment by Keith94** [comment]
It's fixed on my end now. Thanks!
