### ISSUE TITLE
Add date to custom formatting

### ISSUE THREAD

**Issue by Keith94** [Flozad/copy-all-urls-extension#2]
Can we please use `$date` to copy today's date in our custom format, i.e. YYYY-MM-DD or 2024-09-15 (the main reason I need this add-on)

**Comment by Flozad** [comment]
Implemented this change on the source code. Waiting for Google to approve the V1.2.0. I'll close this once it is out.

cc @Keith94

**Comment by Keith94** [comment]
Wow! That was fast. Excited to try it.

**Comment by Flozad** [comment]
Live now.
<img width="400" alt="image" src="https://github.com/user-attachments/assets/2e33b12e-9c82-48fe-95fa-9bedacf4d326">

**Comment by Keith94** [comment]
Awesome! thanks
