### ISSUE TITLE
Paste URL broken

### ISSUE THREAD

**Issue by Keith94** [Flozad/copy-all-urls-extension#3]
Pasting https://www.inoreader.com/all_articles with custom format `<ref>{{Refurl|url=$url|title=$title}}</ref>` results in this:

>chrome-extension://djdmadneanknadilpjiknlnanaolmbfk/%3Cref%3E%7B%7BRefurl%7Curl=https://www.inoreader.com/all_articles%7Ctitle=Inoreader%20-%20All%20articles%7Cdate=%7D%7D%3C/ref%3E

**Comment by Flozad** [comment]
The custom state seemed not to be syncing correctly on production. I implemented a change that should fix this; I'll keep you in the loop once Google approves this.

Thanks for bringing the issues up.

cc @Keith94

**Comment by Flozad** [comment]
@Keith94, can you confirm whether this was solved on your side? I tested, and it works, but let me know.

**Comment by Keith94** [comment]
In 1.2.0 it's still not working. same results

**Comment by Flozad** [comment]
It has problems extracting the URL using custom formatting. I submitted a new version. Let's hope that fixes the error on your end. It's v1.3

**Comment by Flozad** [comment]
@Keith94, it was updated in Chrome. If you confirm it works on your side, I'll move forward and close.

**Comment by Keith94** [comment]
Oddly the button doesn't paste anything, and when I press the button it scrolls to the bottom of the current page. This happens even if I copied a URL by itself without any extra text

**Comment by Flozad** [comment]
Strange. This is how I'm returning the URL. Is there something different you are trying to do?

https://github.com/user-attachments/assets/b914d912-ba13-4a91-b0a1-41f7ba43e28b

**Comment by Keith94** [comment]
No, I'm trying to do the same as you. I'm also using Brave, I don't know if that makes a difference though.

**Comment by Flozad** [comment]
@Keith94 try using a format that contains href="",

Like this <ref href="$url">{{Refurl|url=$url|title=$title|date=$date}}</ref>

**Comment by Keith94** [comment]
With your above snippet it works great !

It doesn't however work with just plain URLs that I copied e.g. with ctrl+c from address bar or some other means.

Maybe I'm just misunderstanding how the button is supposed to work in the first place...?

**Comment by Flozad** [comment]
Now that I added the textarea in the popup, you can copy it elsewhere and paste it into the input. Remember that it needs to match the text format marked in the options.

let me know if something else comes up or doesn't work on your side.
