### ISSUE TITLE
Copy URL and Paste URL don't work

### ISSUE THREAD

**Issue by casualsailo** [Flozad/copy-all-urls-extension#4]
With manifest v2 being deprecated, I'm looking for a replacement to the "Copy All URLs" extension by Vincent and stumbled on this extension

However, I'm having trouble getting it to work. I have V1.4.2 installed

1. When clicking "Copy URL", the links shown in the text box is for the last opened window. It doesn't show the links for the current window. This looks like a bug

2. In addition, it also doesn't copy the links to my clipboard. I am expecting clicking "Copy URL" to copy the links to my clipboard, and then I can paste Ctrl + V onto a text editor. Does the extension copy the links to the clipboard?

3. I can't figure out how to get "Paste URL" to work. I have links copied onto my clipboard, but when I click "Paste URL", nothing happens. I am expecting the links to open. How do you use this?

Thank you!

**Comment by casualsailo** [comment]
If it helps, these are my settings
![Umbrella - Copy All URLs V3 settings](https://github.com/user-attachments/assets/2ff4d144-c84b-456a-94ea-35079dc13699)

**Comment by Flozad** [comment]
Hey, @casualsailo, thanks for bringing this up. I messed up the core idea of the clipboard with the textarea implementation. Version 1.5.0 includes both ideas. I've been quite low on time lately, but let me know if it accomplishes your use case now or if you would like to add something else.

**Comment by Flozad** [comment]
For the custom format, use something like this (href="$url") to make it work. It is hard to detect the $url alone.

**Comment by casualsailo** [comment]
Thanks for working on this!

I tested v1.5.0, and can verify that clicking "Copy URL" shows the links for the current window, and copies to the clipboard.

In the settings page, there is a "Smart Paste" checkbox. I thought if that was unchecked, when clicking "Paste URL", the extension would treat it as one url per line. If that is not how it works, is that a feature you could add?

I was able to get "Paste URL" to work by changing custom format to (href="$url"), but I ideally would like it to work as one url per line.

In addition, I noticed that pasting URLs only seems to open the https links. It doesn't open the other stuff like chrome://, chrome-extension://, file:///, etc. Are you able to allow the extension to open all links without checking if it is a https one?

I see the 2 radio buttons for pasting from clipboard/textarea. I noticed the extension doesn't remember the last setting; it always defaults to pasting from clipboard.

Thanks

**Comment by Flozad** [comment]
@casualsailo, thanks again for the great details.

Changes:
When you click "Copy URL," it displays how many URLs were copied.

By unchecking "Smart Paste" in the settings, you can choose to treat each line as a separate URL during paste operations.

The extension now attempts to open all types of URLs during paste, including Chrome://, chrome-extension://, file:///, and others. However, Chrome has some security policies, so some aren't open.

It remembers your last selected paste source (clipboard or textarea)

If you run into more ideas, I'd love to add them.

I'm waiting for version 1.5.1 to be approved, likely in 1 hour.

**Comment by casualsailo** [comment]
Was there an issue with the approval process? It's still showing version 1.5.0 on the chrome web store

**Comment by Flozad** [comment]
@casualsailo, it's live now.

**Comment by casualsailo** [comment]
It's working great!

Just wanted to note that I needed to enable "Allow access to file URLs" for file:/// pages to open

When "Smart Paste" is checked, **chrome-extension://** pages is opening as **extension://**. So although the tab is created, it doesn't open the correct page

**Comment by Flozad** [comment]
Moving this tweak to https://github.com/Flozad/copy-all-urls-extension/issues/5

Thanks for the feedback!

For other folks here, you need to have this setting 'ON' to open local files
![image](https://github.com/user-attachments/assets/83d1b479-bd07-478c-93e4-f45224770488)
